The 2.6.18 milestone with some success in /usr merge

diff --git a/linux-2.6.18/man/BUILD b/linux-2.6.18/man/BUILD
--- a/linux-2.6.18/man/BUILD
+++ b/linux-2.6.18/man/BUILD
@@ -1,32 +1,15 @@
 # CorePKG build script for man.
-# Copyright 2010-2024 David Egan Evans
-#
-# This program is free software; you can redistribute it and/or modify it under
-# the terms of the GNU General Public License as published by the Free Software
-# Foundation; either version 2 of the License, or (at your option) any later
-# version.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License along with
-# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
-# Place, Suite 330, Boston, MA 02111-1307 USA
-
 DIST=deevans
 PKG=man
 VERSION=1.6g
-ARCH=pentium3
+ARCH=i486
 
 if test ! -w .
-then echo 'Cannot write to this directory!' 1>&2
-	exit 2
+then echo 'Cannot write to this directory!' 1>&2; exit 2
 fi
 
 if test ! -f core.info
-then echo "The core.info file is not present." 1>&2
-	exit 3
+then echo "The core.info file is not present." 1>&2; exit 3
 fi
 
 if test -d /tmp/$DIST-$PKG/
@@ -36,15 +19,14 @@ fi
 if test -d $PKG-$VERSION/
 then rm -r $PKG-$VERSION/
 fi
-if test -f SHA384.txt
-then sha384sum -c SHA384.txt || exit 4
+if test -f SHA1.txt
+then sha1sum -c SHA1.txt || exit 4
 fi
-tar xjf $PKG-$VERSION.tar.bz2
+tar xzf $PKG-$VERSION.tar.gz
 cd $PKG-$VERSION || exit 5
 
-./configure +lang en -confdir /etc
+./configure +traditional +lang en -confdir /etc
 CC=gcc CFLAGS="-Os -march=$ARCH" make all || exit 6
-
 mkdir -p /tmp/$DIST-$PKG/usr/man/man{1,5,8}/
 mkdir -p /tmp/$DIST-$PKG/usr/bin/
 for i in man whatis apropos
@@ -54,6 +36,13 @@ done
 cp man2html/man2html /tmp/$DIST-$PKG/usr/bin/
 cp man2html/man2html.1 /tmp/$DIST-$PKG/usr/man/man1/
 cp man/en/man.conf.man /tmp/$DIST-$PKG/usr/man/man5/man.conf.5
+
+sed -i '/^AWK/ s/^/#/' src/makewhatis
+sed -i '/^# AWK/ s/^# //' src/makewhatis
+sed -i '/^DEFMANPATH/ cDEFMANPATH=/usr/man' src/makewhatis
+sed -i '/^DEFCATPATH/ cDEFCATPATH=' src/makewhatis
+sed -i '/^sections/ s/ n l//' src/makewhatis
+sed -i '/^for\ name/ s/$/ -w/' src/makewhatis
 
 cp src/makewhatis /tmp/$DIST-$PKG/usr/bin/
 cp man/en/makewhatis.8 /tmp/$DIST-$PKG/usr/man/man8/
diff --git a/linux-2.6.18/module-init-tools/BUILD b/linux-2.6.18/module-init-tools/BUILD
--- a/linux-2.6.18/module-init-tools/BUILD
+++ b/linux-2.6.18/module-init-tools/BUILD
@@ -1,5 +1,5 @@
 # CorePKG build script for modutils.
-# Copyright 2010-2024 David Egan Evans
+# Copyright 2010-2025 David Egan Evans
 #
 # This program is free software; you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software
@@ -17,8 +17,7 @@
 DIST=deevans
 PKG=module-init-tools
 VERSION=3.12
-ARCH=pentium3
-TARGET=i686
+ARCH=i486
 
 if test ! -w .
 then echo 'Cannot write to this directory!' 1>&2; exit 2
@@ -35,39 +34,38 @@ fi
 if test -d $PKG-$VERSION/
 then rm -r $PKG-$VERSION/
 fi
-if test -f SHA384.txt
-then sha384sum -c SHA384.txt || exit 4
+if test -f SHA1.txt
+then sha1sum -c SHA1.txt || exit 4
 fi
 tar xjf $PKG-$VERSION.tar.bz2
 cd $PKG-$VERSION || exit 5
 
-# A build failure with/since 3.2:
+# This resolves a build failure with/since 3.2:
 echo .so modprobe.conf.5 > modprobe.d.5
 
 CFLAGS="-Os -march=$ARCH" \
 ./configure \
+	--build=$ARCH-$DIST-linux-gnu \
+	--disable-nls \
+	--mandir=/usr/man \
 	--prefix=/usr \
 	--sbindir=/usr/bin
-#        --mandir=/usr/man
-# --disable-nls doesn't work but there's no i18n files either:
-#	--disable-nls
-# Why does this make files with this name, e.g. i386-deevans-linux-gnu-cmd
-#	--build=$TARGET-$DIST-linux-gnu \
-#	--host=$TARGET-$DIST-linux-gnu \
-#	--target=$TARGET-$DIST-linux-gnu 
 make || exit 6
 make install DESTDIR=/tmp/$DIST-$PKG/
+
+mv /tmp/$DIST-$PKG/usr/share/man/ /tmp/$DIST-$PKG/usr/
+rmdir /tmp/$DIST-$PKG/usr/share/
+
+# Core did not include .2 manuals:
+#rm -r /tmp/$DIST-$PKG/usr/man/man2/
+
+#echo .so man8/insmod.8 > /tmp/$DIST-$PKG/usr/man/man8/insmod_ksymoops_clean.8
+
+find /tmp/$DIST-$PKG/usr/man/ -type f -exec bzip2 -9 {} \;
 
 mkdir /tmp/$DIST-$PKG/sbin/
 mv /tmp/$DIST-$PKG/usr/bin/insmod.static /tmp/$DIST-$PKG/sbin/insmod
 chmod 750 /tmp/$DIST-$PKG/sbin/*
-
-# Coredistro did not include .2 manuals (modutils-doc?):
-#rm -r /tmp/$DIST-$PKG/usr/man/man2/
-
-mv /tmp/$DIST-$PKG/usr/share/man/ /tmp/$DIST-$PKG/usr/
-rmdir /tmp/$DIST-$PKG/usr/share/
-find /tmp/$DIST-$PKG/usr/man/ -type f -exec bzip2 -9 {} \;
 
 find /tmp/$DIST-$PKG/ | xargs file | \
 	grep -e "executable" -e "shared object" | \
